[package]
name = "on_youtube"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version ="1.44.2", features = ["full"]}
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["json"] }
regex = "1.11.1"

